version: '2.1'
networks:
  default_network:
services:
  ################################################
  client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app:rw
    environment:
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - default_network
    ports:
      - '3020:80'
